[build]
  publish = "dist"  # Thư mục chứa các file build (thường là dist với Vite)
  command = "npm run build"  # Lệnh build ứng dụng

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
